# Generated by Django 4.0.4 on 2022-05-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_text', models.CharField(max_length=160)),
                ('deadline', models.DateField()),
                ('progress', models.IntegerField(default=0)),
            ],
        ),
    ]
