# Generated by Django 4.0.4 on 2022-05-19 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Task_text',
            new_name='task_text',
        ),
    ]
